.gitlab-ci.yml

This ensures the desired branch is available. I'm not sure if there are any other implications by running this, so please check.
This closes #9.

Run `git fetch` before switching branches

---

.gitlab-ci.yml

This enables caching for imported assets between each run. This massively speeds up the export stage for big projects (which needs ~30 minutes to import 150MB for a 3D project).
Note that this saves the cache *after* a stage is done so it is not shared by the 3 platforms if they run in parallel. So if you add new files it will still import them once for each platform (but will not import them again in the future, which is what matters).

Add caching for imported assets

---

README.md
mono.Dockerfile

This does the required changes to build a godot+mono in a docker container.
I think we might want to make a separate branch for mono and merge this to that.
Note that this only changes the Dockerfile and does not edit the `gitlab-ci.yml` since I think we will want to link to a different dockerhub
Part of https://github.com/aBARICHELLO/godot-ci/issues/17

Build mono docker image

---

mono.Dockerfile

When I submitted the image in https://github.com/aBARICHELLO/godot-ci/pull/16 I made it use the stable version so we can build 3.2.1 from the master branch.
I've been using the beta for a while so I already tested this (see [builds here](https://hub.docker.com/repository/docker/asheraryam/godot-mono-ci/tags?page=1) on dockerhub).
If you'd like I can also submit a similar PR for the non-mono version.

Use latest beta for mono image

---

.github/workflows/godot-ci.yml

This lets godot-ci.yml deploy to GitHub Pages after a Web Build is exported. Thanks to https://github.com/JamesIves/github-pages-deploy-action
If you encounter issues when deploying to gh-pages, try to change the theme from the repository's settings.
This addresses a part of #14.

Deploy to GitHub Pages from GitHub Actions

---

README.md

First of all, thanks so much for maintaining this project and always making sure that you have a new Docker image up when new Godot versions come out! It's wonderful that the community has this valuable resource available. :-)
I noticed that you put a link to Kyle Luce's video tutorial in the README.md, and I was wondering if you'd be willing to put a link to my video tutorial series as well?
The first part is up and it covers using this image for exporting to Windows, Linux, Windows and HTML5, and deploying to GitLab Pages. Future parts will cover deploying to Itch.io (and other places), more advanced exports (ex. Android) and using custom builds of Godot.
Anyway, thanks again for your work on this project! I'd love to chat sometime via email or Discord or whatever. :-)

Add a link to David Snopek's video tutorial series about Godot and GiitLab CI

---

mono.Dockerfile

The engine changes do not affect the docker process so changing the version variable in the script is all we need to do.

Update mono docker to 3.2.3

---

.gitlab-ci.yml
README.md

Hello!
When setting up the Android Release CI on Gitlab there was some confusion regarding the necessary **type** of variable that had to be created. Since the README and YML both clearly state that it has to be saved a file-type CI variable while the YML commands expect to receive a variable (with the echo-command).
After a short discussion with @asheraryam it was decided that, to avoid any further confusion, this should be updated.
Also, since base64 is not natively available on Windows OS, I added a native command that does the same thing in Windows, so poor users don't have to download any external software and can just exploit the native toolset 😢 
Greetings!

Add base64 command for windows, Fix type from variable to file

---

Dockerfile
mono.Dockerfile

This image is great, but my project uses LFS, and without it, causes builds to think that assets are corrupt.
Would love to get this added here, and the image pushed to Dockerhub.
If not, you guys have any suggestions on how to use your Dockerfile in an easy way?

feature(lfs): add dependency to image

---

.github/workflows/godot-ci.yml
Dockerfile

So regarding #43 and my last pull request adding git lfs to the dependencies; to actually be able to use LFS in the actions pipeline, you need a minimum of git version 2.18.
Ubuntu Bionic defaults to 2.17.1 :frowning: 
There are two solutions here, to use `ubuntu: focal` as the image (the current LTS build)
Or add the PPA repository while installing the other dependencies
```
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git
```
Not sure which one falls better in line with the strategy of Godot-CI? However, I'm not sure how that might affect the Mono Dockerfile, since I can't really find what that image is based on.

chore(git): version for LFS dependency

---

README.md

This adds links to external projects that cover areas that we miss. We can possibly expand to include some of them later, like C++ compilation, but until then it's necessary to refer to them.
This mentions @2shady4u @Calinou [@Greenfox](https://gitlab.com/greenfox)

Add additional resources for other CI needs

---

.gitlab-ci.yml

It seems that the workdir for gitlab is already inside the cloned repo,
so `cd $EXPORT_NAME` will fail.
Here's a build that prints `pwd` to demonstrate:
https://gitlab.com/rcorre/weekly-game-jam-204/-/jobs/1318895344
Here's a pipeline that passed after removing `cd`:
- https://gitlab.com/rcorre/weekly-game-jam-204/-/pipelines/315008027
- https://gitlab.com/rcorre/weekly-game-jam-204/-/commit/1af90b1fa2b9b74abb3e50a022809d700350bc10.

Remove needless cd from gitlab-ci.

---

Dockerfile

Just added downloading of android-sdk and installing all required components. With these changes export for android should work correctly.
Should fix #59 
Also removed settings for adb and jarsigner, as mentioned [here](https://github.com/abarichello/godot-ci/issues/68#issuecomment-987301272)

Add downloading of android-sdk and required components

---

.github/workflows/godot-ci.yml

The last release of v3 was in 2020.
This PR follows the migration guide: https://github.com/JamesIves/github-pages-deploy-action/discussions/592.
The input parameters are now lowercase, and the token is now automatically taken from the environment.

Update version of github-pages-deploy-action used in templates

---

Dockerfile

I got a problem related to Android Release with custom build template.
```
* What went wrong:
A problem occurred evaluating root project 'build'.
> Failed to apply plugin 'com.android.internal.application'.
> Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
You can try some of the following options:
- changing the IDE settings.
- changing the JAVA_HOME environment variable.
- changing `org.gradle.java.home` in `gradle.properties`.
```
The solution is simple to install jdk-11 instead of jdk-8. Jdk8 is almost out of support anyway

Update Java version to 11

---

.github/workflows/check-release.yml
.github/workflows/godot-ci.yml
.github/workflows/release.yml
Dockerfile
mono.Dockerfile

This PR resolves #65 and #75 by adding a workflow `.github/workflows/check-release.yml` that runs every night at 23:27 UTC and compares the tag in the latest release of https://github.com/godotengine/godot/releases with the latest tag in this repository. Ideally we would be notified of new releases, but it looks like this would require setting up a [`repository_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch) event on the main Godot repo or something similar.
In case the two tags differ, it will automatically create an equivalent tag in this repository and generate a new release. The body of the release is copied from the release in the engine repository. 
When a new release is created `.github/workflows/release.yml` is …

Automate image release process

---

.github/workflows/manual_build.yml
Dockerfile
mono.Dockerfile

adds `.github/workflows/manual_build.yml` which allows manually generating docker images for specific Godot versions. 
The primary use case of this is creating images for pre-release builds since they are not marked with a release in the official GitHub repository. It's also a useful way of generating images for any release that might have gotten skipped, such as https://github.com/abarichello/godot-ci/issues/75
the generated images will be tagged with the release name, unless the release name is `stable`
- **3.5 rc3** -> `godot-ci:3.5.rc3` & `godot-ci:mono-3.5.rc3`
- **3.4.4 stable** -> `godot-ci:3.4.4` & `godot-ci:mono-3.4.4`

Add a Manual Build workflow

---

.github/workflows/check-release.yml

Fixes #91 
The root cause of the issue was in the fact that GitHub actions doesn't respect shell scripting conventions, but instead replaces `${{ whatever }}` by injecting the value of the variable directly into their generated script. 
This created an issue where a single quote that is used by the workflow to ensure json doesn't get messed up got completed by a single quote in the release description, which in turn created an invalid bash script that the workflow tried to execute. 
Instead of prefetching the release information, the workflow now fetches the body and tag name when necessary, using shell scripting the entire way, avoiding action executor weirdness. 
Once merged, everything **should** run normally at 23:27

Use GitHub CLI to fetch release information

---

.github/workflows/check-release.yml
.github/workflows/release.yml

While the release action still uses set-output (and shows deprecation warnings accordingly) I figured at least now them deprecation warnings won't be coming from the godot-ci action 😃

use GITHUB_OUTPUT instead of set-output

---

.github/workflows/godot-ci.yml

add a PROJECT_PATH global to separate the project PATH from the project NAME. This will make the configuration more general as well as add a self documenting quality to the configuration file.

add PROJECT_PATH global.

---

README.md

Previously, the detail that you had to change .stable to .stable.mono in the Setup steps directory structure was not listed and was very confusing for me until I found an issue from some time ago ( https://github.com/abarichello/godot-ci/issues/29#issuecomment-680315417 ) that stated this solution but was never addressed. I hope this can save people some trouble in the future.

Add missing step to C#/Mono tutorial in README.md

---

README.md

This closes https://github.com/abarichello/godot-ci/issues/72.

Improve export troubleshooting notes in the README

---

.gitlab-ci.yml
Dockerfile

I'm not sure these are all the fixes needed for everyone, I don't have a lot of knowledge of platforms other than Android, but I managed to create a docker image that works for my project.
I adapted the changes I made to minimize changes here, since I customized some other things, but I think this should be enough to get builds going for Godot 4.
Any suggestions or comments are welcome, of course.

Fix build for Godot 4

---

.gitlab-ci.yml

Follow-up to https://github.com/abarichello/godot-ci/pull/107.
I noticed the imports directory wasn't right for Godot 4.

Fix imports cache for Godot 4

---

.github/workflows/godot-ci.yml
.gitlab-ci.yml

- Use long-form `--verbose` and `--editor` for better readability.
___
- This closes https://github.com/abarichello/godot-ci/issues/112.

Fix Godot CLI arguments to use `--headless` everywhere

---

Dockerfile

I was able to test locally and updating the JDK indeed fixed my export for Android as reported on #131. This PR updates only the package into the Docker file so please let me know if you need any further changes to make it more flexible.

Update JDK version required for Godot 4.2 Android exports

---

.github/workflows/godot-ci.yml
Dockerfile
README.md
mono.Dockerfile

- This closes https://github.com/abarichello/godot-ci/issues/134.

Fix `export_templates` folder name in Dockerfile and CI scripts

---

.github/workflows/godot-ci.yml

So due to solving my previous problem #134 (thank you), I was able to finally setup the pipeline to export.
However, I noticed some warning messages that popped up, stating that the checkout action this project uses is deprecated:
So I checked the [link](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) and it recommended to upgrade the checkout action to a newer release by just [changing the version number](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions)
I tested it on my own project, changing the version number (exporting Windows + macOS) and it works perfectly fine now with the annotations being gone.
I'm not sure if there is anything in the other export platforms that …

Update GH Action checkout to v4

---

.github/workflows/godot-ci.yml
.github/workflows/manual_build.yml
.gitlab-ci.yml
Dockerfile
mono.Dockerfile

Updated godot-ci to use 3.6 + export templates.

Added 3.6 CI Version

---

.github/workflows/release.yml
Dockerfile
mono.Dockerfile

`editor_settings.tres` is now split per minor version since 4.3.
This also updates `mono.Dockerfile` to match the main `Dockerfile`.
- See https://github.com/abarichello/godot-ci/issues/148.

Update for Godot 4.3

---

.github/workflows/godot-ci.yml
.gitlab-ci.yml

- Automatically adapt the export folder based on project folder location relative to the repository root.
- Update workflow files to use Godot 4.3.
- Update default export prest names to match Godot 4.0 onwards.
___
- This closes https://github.com/abarichello/godot-ci/issues/144.

Fix invalid paths in GitHub Actions and GitLab CI workflow files

---

.github/workflows/godot-ci.yml

```md
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

Fix actions: using upload-artifact@v4

---

Dockerfile
mono.Dockerfile

Looks like the tuxfamily download site is down, and its undetermined if/when it will be restored (see forum link below)
https://forum.tuxfamily.org/post/3388/#p3388
I updated the docker file to use the main godot link (was there a reason it wasn't using that?)

4.4 docker fix

---

.github/workflows/manual_build.yml

Can be used to close #171 
I hope I didn't break anything with the secrets/environments, it works on my machine™
Why are we using artifacts instead of setting a job output?
Because GitHub actions helpfully detects the usage of a secret string `DOCKERHUB_USERNAME` and wipes the job output. If we change DOCKERHUB_USERNAME to an environment variable, set in the repository, then this can be further simplified.

enable tagging with latest based on user input in manual workflow

---

.github/workflows/check-release.yml
.github/workflows/godot-ci.yml
.github/workflows/manual_build.yml
.github/workflows/release.yml
Dockerfile
mono.Dockerfile

godot 4.5 has released and it removes the rcedit requirement as it can now directly manipulate resources, ubuntu 22.04 is losing extended support in a year so i just bumped that, godot still works fine (tested in distrobox)

bump to newer ubuntu, and godot 4.5, remove rcedit
